# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:slim-bookworm

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install essential packages, including build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# Set the working directory to /app
WORKDIR /app

# Copy the application code
COPY app/server.py /app/server.py

# Copy the requirements file
COPY app/requirements.txt /app/requirements.txt

# Install dependencies with pip
RUN pip install -r requirements.txt


# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# Expose port 8000 for FastAPI
EXPOSE 8000

# Command to start the FastAPI server with pip
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]